### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by andreypfau** [SoRadGaming/Simple-HUD-Enhanced#18]
<img width="902" alt="image" src="https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/97797573/55b866ef-0fe0-493c-bb64-652e6a511dc7">

1.81 GB for config?
After 3-4 hours of playing its takes about 2 GB and minecraft become unplayable due GC

<img width="859" alt="image" src="https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/97797573/f2a8bc51-cfa3-4d5a-a019-148fa34efe23">
1.2 million instances for Equipment class is not normal i think

**Comment by andreypfau** [comment]
<img width="980" alt="image" src="https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/97797573/90e288fd-e467-4415-9bc2-19f459493df1">
Saving events in list is very bad practice.

**Comment by SoRadGaming** [comment]
What Mod Version is this? I fixed the equipment class leak bug in 4.2.0, and config instances are fixed in update 4.3.0. What do you mean _"Saving events in list is very bad practice. "_? The main issue with config is that the autocofing library doesn't handle gc properly, so I'm only calling one instance instead of 3.

**Comment by SoRadGaming** [comment]
> <img alt="image" width="980" src="https://user-images.githubusercontent.com/97797573/280414466-90e288fd-e467-4415-9bc2-19f459493df1.png"> Saving events in list is very bad practice.

That's not what the issue was lol.
