### ISSUE TITLE
Support for trinkets slots

### ISSUE THREAD

**Issue by Nemo157** [SoRadGaming/Simple-HUD-Enhanced#24]
When using [Elytra Trinket](https://modrinth.com/mod/elytra_trinket) to equip an elytra in a trinket slot its durability is not shown in the equipment HUD. Detecting when [Trinkets](https://modrinth.com/mod/trinkets) is installed and adding it to the list of slots to be checked would be useful.

**Comment by SoRadGaming** [comment]
I implemented the API in a test. As you can see in the image below, it seems to work. The only issue is the Order and Incompatibility with Equipment Settings (Only Slots/Durability is an Issue). Also, the Triknet API has some problems that must be worked out. For example, not installing the mod just breaks the classes it's used instead of throwing an error.

**Image:**
![image](https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/47128515/e1cde45e-671f-4547-8323-38c3fda37c00)

**Comment by SoRadGaming** [comment]
Got Everything Working Perfectly. The only issue is the API is required for using the mod now, so I need to fix this issue, then I can proceed.
